### ISSUE TITLE
An incomplete trace is generated for Time-11 arja-plausible with depth 3

### ISSUE THREAD

**Issue by algomaster99** [ASSERT-KTH/collector-sahab#183]
The trace is already 5.1 GB. I think jackson does not serialise all objects and gives up in between. Serialisation optimisation is needed.

```sh
java -jar /home/aman/assert-achievements/collector-sahab/main/target/collector-sahab-0.1.4-SNAPSHOT-jar-with-dependencies.jar  -p /home/aman/experiments/drr-execdiff/Time-11 -c src/main/java/org/joda/time/tz/DateTimeZoneBuilder.java -l e5d67a8 -r 20e5b8c28c217749dbba407416cae169df3c3fd7 --slug 'ASSERT-KTH/collector-sahab-experiments' --execution-depth 3 --selected-tests "org.joda.time.tz.TestCompiler#testDateTimeZoneBuilder"
```

<details>
<summary>Trace</summary>

```sh

com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input within/between Object entries
 at [Source: (FileReader); line: 113003764, column: 1] (through reference chain: se.assertkth.cs.commons.runtime.output.SahabOutput["breakpoint"]->java.util.ArrayList[6890]->se.assertkth.cs.commons.runtime.LineSnapshot["stackFrameContext"]->java.util.ArrayList[0]->se.assertkth.cs.commons.runtime.StackFrameContext["runtimeValueCollection"]->java.util.ArrayList[12]->se.assertkth.cs.commons.runtime.RuntimeValue["fields"]->java.util.ArrayList[26]->se.assertkth.cs.commons.runtime.RuntimeValue["fields"]->java.util.ArrayList[6]->se.assertkth.cs.commons.runtime.RuntimeValue["fields"]->java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:373)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:375)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3698)
        at se.assertkth.tracediff.statediff.computer.StateDiffComputer.getFirstDistinctStateOnRelevantLine(StateDiffComputer.java:162)
        at se.assertkth.tracediff.statediff.computer.StateDiffComputer.computeProgramStateDiff(StateDiffComputer.java:48)
        at se.assertkth.tracediff.statediff.ui.StateDiffUIManipulator.addStateDiffToExecDiffUI(StateDiffUIManipulator.java:91)
        at se.assertkth.tracediff.statediff.StateDiffCommand.call(StateDiffCommand.java:73)
        at se.assertkth.tracediff.statediff.StateDiffCommand.call(StateDiffCommand.java:9)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at se.assertkth.tracediff.ExecDiffMain.main(ExecDiffMain.java:18)
        at se.assertkth.cs.Main.call(Main.java:164)
        at se.assertkth.cs.Main.call(Main.java:27)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at se.assertkth.cs.Main.main(Main.java:80)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input within/between Object entries
 at [Source: (FileReader); line: 113003764, column: 1]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2418)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipAfterComma2(ReaderBasedJsonParser.java:2511)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2481)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:716)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:423)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        ... 78 more
```

</details>

**Comment by algomaster99** [comment]
Give jackson's [streaming API](https://www.baeldung.com/jackson-streaming-api) a try.

**Comment by algomaster99** [comment]
<details>
<summary>Failed attempt</summary>

```diff
diff --git a/trace-collector/src/main/java/io/github/chains_project/collector/CollectorAgent.java b/trace-collector/src/main/java/io/github/chains_project/collector/CollectorAgent.java
index b62de99..f536a9c 100644
--- a/trace-collector/src/main/java/io/github/chains_project/collector/CollectorAgent.java
+++ b/trace-collector/src/main/java/io/github/chains_project/collector/CollectorAgent.java
@@ -4,6 +4,9 @@ import static org.objectweb.asm.Opcodes.ATHROW;
 import static org.objectweb.asm.Opcodes.IRETURN;
 import static org.objectweb.asm.Opcodes.RETURN;
 
+import com.fasterxml.jackson.core.JsonEncoding;
+import com.fasterxml.jackson.core.JsonFactory;
+import com.fasterxml.jackson.core.JsonGenerator;
 import com.fasterxml.jackson.core.util.DefaultIndenter;
 import com.fasterxml.jackson.core.util.DefaultPrettyPrinter;
 import com.fasterxml.jackson.databind.ObjectMapper;
@@ -13,13 +16,23 @@ import io.github.chains_project.collector.util.ContextCollector;
 import io.github.chains_project.cs.commons.CollectorAgentOptions;
 import io.github.chains_project.cs.commons.FileAndBreakpoint;
 import io.github.chains_project.cs.commons.MethodForExitEvent;
+import io.github.chains_project.cs.commons.runtime.LineSnapshot;
 import io.github.chains_project.cs.commons.runtime.LocalVariable;
+import io.github.chains_project.cs.commons.runtime.RuntimeReturnedValue;
+import io.github.chains_project.cs.commons.runtime.RuntimeValue;
+import io.github.chains_project.cs.commons.runtime.StackFrameContext;
+import io.github.chains_project.cs.commons.runtime.output.SahabOutput;
 import io.github.chains_project.cs.commons.util.Classes;
+
+import java.io.ByteArrayOutputStream;
+import java.io.File;
 import java.io.IOException;
 import java.io.PrintWriter;
 import java.lang.instrument.ClassFileTransformer;
 import java.lang.instrument.Instrumentation;
 import java.lang.reflect.Modifier;
+import java.nio.charset.StandardCharsets;
+import java.nio.file.Files;
 import java.security.ProtectionDomain;
 import java.util.ArrayList;
 import java.util.List;
@@ -87,15 +100,64 @@ public class CollectorAgent {
                 true);
         Runtime.getRuntime().addShutdownHook(new Thread(() -> {
             try {
-                new ObjectMapper()
-                        .writer(new DefaultPrettyPrinter().withArrayIndenter(new DefaultIndenter("  ", "\n")))
-                        .writeValue(options.getOutput(), ContextCollector.getSahabOutput());
+                streamOutputIntoJson(ContextCollector.getSahabOutput(), options.getOutput());
             } catch (IOException e) {
-                e.printStackTrace();
+                throw new RuntimeException(e);
             }
+            //                new ObjectMapper()
+            //                        .writer(new DefaultPrettyPrinter().withArrayIndenter(new DefaultIndenter("  ",
+            // "\n")))
+            //                        .writeValue(options.getOutput(), ContextCollector.getSahabOutput());
+
         }));
     }
 
+    private static void streamOutputIntoJson(SahabOutput output, File outputFile) throws IOException {
+        ByteArrayOutputStream stream = new ByteArrayOutputStream();
+        JsonFactory jfactory = new JsonFactory();
+        JsonGenerator jGenerator = jfactory.createGenerator(stream, JsonEncoding.UTF8);
+        jGenerator.writeStartObject();
+        jGenerator.writeFieldName("breakpoint");
+        jGenerator.writeStartArray();
+        for (LineSnapshot breakpoint: output.getBreakpoint()) {
+            jGenerator.writeStartObject();
+            jGenerator.writeStringField("file", breakpoint.getFile());
+            jGenerator.writeNumberField("line", breakpoint.getLineNumber());
+            jGenerator.writeFieldName("stackFrameContext");
+            jGenerator.writeStartArray();
+            for (StackFrameContext stackFrameContext: breakpoint.getStackFrameContext()) {
+                jGenerator.writeStartObject();
+                jGenerator.writeNumberField("positionFromTopInStackTrace", stackFrameContext.getPositionFromTopInStackTrace());
+                jGenerator.writeStringField("location", stackFrameContext.getLocation());
+                jGenerator.writeFieldName("stackTrace");
+                jGenerator.writeStartArray();
+                for (String st: stackFrameContext.getStackTrace()) {
+                    jGenerator.writeString(st);
+                }
+                jGenerator.writeEndArray();
+                jGenerator.writeFieldName("runtimeValueCollection");
+                jGenerator.writeStartArray();
+                for (RuntimeValue runtimeValue: stackFrameContext.getRuntimeValueCollection()) {
+            new ObjectMapper().writer(new DefaultPrettyPrinter().withArrayIndenter(new DefaultIndenter("  ", "\n"))).writeValue(jGenerator, runtimeValue);
+
+                }
+                jGenerator.writeEndArray();
+                jGenerator.writeEndObject();
+            }
+        }
+        jGenerator.writeEndArray();
+        jGenerator.writeFieldName("return");
+        jGenerator.writeStartArray();
+        for (RuntimeReturnedValue returnedValue: output.getReturns()) {
+            new ObjectMapper().writer(new DefaultPrettyPrinter().withArrayIndenter(new DefaultIndenter("  ", "\n"))).writeValue(jGenerator, returnedValue);
+        }
+        jGenerator.writeEndArray();
+        jGenerator.writeEndObject();
+        jGenerator.close();
+
+        String content = new String(stream.toByteArray(), StandardCharsets.UTF_8);
+        Files.writeString(outputFile.toPath(), content);
+    }
     private static List<String> getClassesAllowed() {
         List<FileAndBreakpoint> fileAndBreakpoints = options.getClassesAndBreakpoints();
         List<MethodForExitEvent> methodForExitEvents = options.getMethodsForExitEvent();
diff --git a/trace-collector/src/test/resources/basic-math/pom.xml b/trace-collector/src/test/resources/basic-math/pom.xml
index 47db1ad..caf39a5 100644
--- a/trace-collector/src/test/resources/basic-math/pom.xml
+++ b/trace-collector/src/test/resources/basic-math/pom.xml
@@ -21,7 +21,7 @@
                 <version>3.0.0</version>
                 <configuration>
                     <!-- To debug: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -->
-                    <argLine>-javaagent:../../../../target/classes/trace-collector.jar=classesAndBreakpoints=src/test/resources/basic-math.txt,methodsForExitEvent=src/test/resources/basic-math.json</argLine>
+                    <argLine> -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005 -javaagent:../../../../target/classes/trace-collector.jar=classesAndBreakpoints=src/test/resources/basic-math.txt,methodsForExitEvent=src/test/resources/basic-math.json</argLine>
                 </configuration>
             </plugin>
         </plugins>

```

</details>

**Comment by algomaster99** [comment]
I am not focussing on optimization right now. It is a todo after GitHub action implementation.
