### ISSUE TITLE
Cannot pop operand off stack

### ISSUE THREAD

**Issue by algomaster99** [ASSERT-KTH/collector-sahab#215]
### Repairnator

There is some instrumentation problem on repairnator.

**Stacktrace**

```sh
Running org.apache.commons.math.analysis.solvers.BrentSolverTest
rtf.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 82: Cannot pop operand off an empty stack.
	at rtf.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:273)
	at rtf.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
	at rtf.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1032)
	at io.github.chains_project.collector.CollectorAgent.getBytes(CollectorAgent.java:179)
	at io.github.chains_project.collector.CollectorAgent$1.transform(CollectorAgent.java:80)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.apache.commons.math.analysis.solvers.BrentSolverTest.testQuinticZero(BrentSolverTest.java:130)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:81)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.lang.IndexOutOfBoundsException: Cannot pop operand off an empty stack.
	at rtf.org.objectweb.asm.tree.analysis.Frame.pop(Frame.java:258)
	at rtf.org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:396)
	at rtf.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:165)
	... 40 more
rtf.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 324: Cannot pop operand off an empty stack.
	at rtf.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:273)
	at rtf.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
	at rtf.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1032)
	at io.github.chains_project.collector.CollectorAgent.getBytes(CollectorAgent.java:179)
	at io.github.chains_project.collector.CollectorAgent$1.transform(CollectorAgent.java:80)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.apache.commons.math.analysis.solvers.BrentSolverTest.testQuinticZero(BrentSolverTest.java:130)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:81)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)
Caused by: java.lang.IndexOutOfBoundsException: Cannot pop operand off an empty stack.
	at rtf.org.objectweb.asm.tree.analysis.Frame.pop(Frame.java:258)
	at rtf.org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:396)
	at rtf.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:165)
	... 40 more
```

### Local (@algomaster99 's machine)

**Command to reproduce**

```sh
java -jar main/target/collector-sahab-0.4.1-SNAPSHOT-jar-with-dependencies.jar -p /home/aman/experiments/drr-execdiff/Math-73 -c src/main/java/org/apache/commons/math/analysis/solvers/BrentSolver.java  --slug ASSERT-KTH/collector-sahab-experiments -l e5d67a8 -r 25c92fbe9ffd72eac6d4829ceb4abcc4a4b5c86e --execution-depth 0 --selected-tests org.apache.commons.math.analysis.solvers.BrentSolverTest --output-path output.html
```

> Specifying the [test method](https://github.com/ASSERT-KTH/collector-sahab-experiments/blob/master/projects-metadata/Math-metadata.csv#L74) does not run any tests.

The process runs successfully, and it generated a diff in return value, but it is not rendered. @khaes-kth could you confirm?

```sh
Apr 27, 2023 11:15:22 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 112, so returning the closest version found: 110
Apr 27, 2023 11:15:43 PM io.github.chains_project.tracediff.statediff.ui.StateDiffUIManipulator addStateDiffToExecDiffUI
INFO: Line mappings and vars computed.
Apr 27, 2023 11:15:43 PM io.github.chains_project.tracediff.statediff.ui.StateDiffUIManipulator addStateDiffToExecDiffUI
INFO: For commit 25c92fbe9ffd72eac6d4829ceb4abcc4a4b5c86e line mappings and vars computation took 22887 MILLIS
Apr 27, 2023 11:15:43 PM io.github.chains_project.tracediff.statediff.ui.StateDiffUIManipulator addStateDiffToExecDiffUI
INFO: ProgramStateDiff{firstOriginalUniqueStateSummary=UniqueStateSummary{differencingTest=null, firstUniqueVarValLine=null, firstUniqueVarVal=null'}, firstPatchedUniqueStateSummary=UniqueStateSummary{differencingTest=null, firstUniqueVarValLine=null, firstUniqueVarVal=null'}, originalUniqueReturn=UniqueReturnSummary{differencingTest=org.apache.commons.math.analysis.solvers.BrentSolverTest, firstUniqueVarValLine=251, firstUniqueVarVal='{return-object}=1.2'}, patchedUniqueReturn=UniqueReturnSummary{differencingTest=null, firstUniqueVarValLine=null, firstUniqueVarVal='null'}}
Apr 27, 2023 11:15:43 PM io.github.chains_project.tracediff.statediff.ui.StateDiffUIManipulator addStateDiffToExecDiffUI
INFO: For commit 25c92fbe9ffd72eac6d4829ceb4abcc4a4b5c86e diff computation took 303 MILLIS
Apr 27, 2023 11:15:43 PM io.github.chains_project.tracediff.statediff.ui.StateDiffUIManipulator addStateDiffToExecDiffUI
INFO: For commit 25c92fbe9ffd72eac6d4829ceb4abcc4a4b5c86e UI manipulation took 39 MILLIS
```

**Comment by algomaster99** [comment]
## patch3-Math-40-Cardumen_e979e14806909f944bc0c70b91ee530657d2ab26

### Repairnator

There is some instrumentation problem on repairnator.

**Stacktrace**

```sh
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.commons.math.analysis.solvers.BracketingNthOrderBrentSolverTest
rtf.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 784: Cannot pop operand off an empty stack.
        at rtf.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:273)
        at rtf.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
        at rtf.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1032)
        at io.github.chains_project.collector.CollectorAgent.getBytes(CollectorAgent.java:179)
        at io.github.chains_project.collector.CollectorAgent$1.transform(CollectorAgent.java:80)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.apache.commons.math.analysis.solvers.BracketingNthOrderBrentSolverTest.testInsufficientOrder1(BracketingNthOrderBrentSolverTest.java:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:21)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:35)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:115)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:97)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
        at com.sun.proxy.$Proxy4.invoke(Unknown Source)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
Caused by: java.lang.IndexOutOfBoundsException: Cannot pop operand off an empty stack.
        at rtf.org.objectweb.asm.tree.analysis.Frame.pop(Frame.java:258)
        at rtf.org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:396)
        at rtf.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:165)
        ... 47 more
Tests run: 15, Failures: 0, Errors: 15, Skipped: 0, Time elapsed: 0.902 sec <<< FAILURE!

Results :

Tests in error:
  testInsufficientOrder1(org.apache.commons.math.analysis.solvers.BracketingNthOrderBrentSolverTest): Unexpected exception, expected<org.apache.commons.math.exception.NumberIsTooSmallException> but was<java.lang.VerifyError>
  testIssue716(org.apache.commons.math.analysis.solvers.BracketingNthOrderBrentSolverTest): Operand stack underflow
Exception Details:
  Location:
    org/apache/commons/math/analysis/solvers/BracketingNthOrderBrentSolver.doSolve()D @1424: dup2
  Reason:
    Attempt to pop empty stack.
  Current Frame:
    bci: @1424
    flags: { }
    locals: { 'org/apache/commons/math/analysis/solvers/BracketingNthOrderBrentSolver', '[D', '[D', top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, 'java/util/List' }
    stack: { 'org/apache/commons/math/exception/NoBracketingException' }
```

**Comment by algomaster99** [comment]
## patch1-Math-70-ssFix_0a682bad1e0b361ffa20b9382203114c4054b88c

Stacktrace

```sh
Running org.apache.commons.math.analysis.solvers.BisectionSolverTest
rtf.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 82: Cannot pop operand off an empty stack.
        at rtf.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:273)
        at rtf.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
        at rtf.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1032)
        at io.github.chains_project.collector.CollectorAgent.getBytes(CollectorAgent.java:179)
        at io.github.chains_project.collector.CollectorAgent$1.transform(CollectorAgent.java:80)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.apache.commons.math.analysis.solvers.BisectionSolverTest.testSetAbsoluteAccuracy(BisectionSolverTest.java:131)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at junit.framework.TestCase.runTest(TestCase.java:168)
        at junit.framework.TestCase.runBare(TestCase.java:134)
        at junit.framework.TestResult$1.protect(TestResult.java:110)
        at junit.framework.TestResult.runProtected(TestResult.java:128)
        at junit.framework.TestResult.run(TestResult.java:113)
        at junit.framework.TestCase.run(TestCase.java:124)
        at junit.framework.TestSuite.runTest(TestSuite.java:232)
        at junit.framework.TestSuite.run(TestSuite.java:227)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:81)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:115)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:102)
        at org.apache.maven.surefire.Surefire.run(Surefire.java:180)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
        at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
Caused by: java.lang.IndexOutOfBoundsException: Cannot pop operand off an empty stack.
        at rtf.org.objectweb.asm.tree.analysis.Frame.pop(Frame.java:258)
        at rtf.org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:396)
        at rtf.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:165)
        ... 40 more
Tests run: 12, Failures: 0, Errors: 12, Skipped: 0, Time elapsed: 0.143 sec <<< FAILURE!

Results :

Tests in error:
  testSetAbsoluteAccuracy(org.apache.commons.math.analysis.solvers.BisectionSolverTest)
  testSetFunctionValueAccuracy(org.apache.commons.math.analysis.solvers.BisectionSolverTest)
  testSetRelativeAccuracy(org.apache.commons.math.analysis.solvers.BisectionSolverTest)
  testResetRelativeAccuracy(org.apache.commons.math.analysis.solvers.BisectionSolverTest)
  testQuinticZero(org.apache.commons.math.analysis.solvers.BisectionSolverTest)
  testMath369(org.apache.commons.math.analysis.solvers.BisectionSolverTest)
  testDeprecated(org.apache.commons.math.analysis.solvers.BisectionSolverTest)
  testSinZero(org.apache.commons.math.analysis.solvers.BisectionSolverTest)
  testResetMaximalIterationCount(org.apache.commons.math.analysis.solvers.BisectionSolverTest)
  testResetFunctionValueAccuracy(org.apache.commons.math.analysis.solvers.BisectionSolverTest)
  testResetAbsoluteAccuracy(org.apache.commons.math.analysis.solvers.BisectionSolverTest)
  testSetMaximalIterationCount(org.apache.commons.math.analysis.solvers.BisectionSolverTest)
```

**Comment by khaes-kth** [comment]
> The process runs successfully, and it generated a diff in return value, but it is not rendered. @khaes-kth could you confirm?

That's what the logs show. I will run it on local to see why this happens.

**Comment by khaes-kth** [comment]
After merging https://github.com/ASSERT-KTH/collector-sahab/pull/223 and rerunning for depth=0, it is now detecting diff for all of these patches! Should not that I only ran it for depth=0 this time; there was no parallel process running collector-sahab.

**Comment by khaes-kth** [comment]
@algomaster99 Should we close this?
