### ISSUE TITLE
Loader 'app' attempted duplicate abstract class definition for org.joda.time.DateTimeZone

### ISSUE THREAD

**Issue by algomaster99** [ASSERT-KTH/collector-sahab#216]
## patch3-Time-17-Cardumen_f8431b4cbe4570108789c8ad6a23f02cab486b05

I am pretty sure I fixed the issue in https://github.com/ASSERT-KTH/collector-sahab/pull/207. Anyhow, shall confirm this later.

**Stacktrace**

```
Running org.joda.time.TestDateTimeZoneCutover
org.apache.maven.surefire.booter.SurefireExecutionException: loader 'app' attempted duplicate abstract class definition for org.joda.time.DateTimeZone. (org.joda.time.DateTimeZone is in unnamed module of loader 'app'); nested exception is java.lang.LinkageError: loader 'app' attempted duplicate abstract class definition for org.joda.time.DateTimeZone. (org.joda.time.DateTimeZone is in unnamed module of loader 'app')
java.lang.LinkageError: loader 'app' attempted duplicate abstract class definition for org.joda.time.DateTimeZone. (org.joda.time.DateTimeZone is in unnamed module of loader 'app')
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
        at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)
        at java.base/java.lang.Class.getMethod0(Class.java:3293)
        at java.base/java.lang.Class.getMethod(Class.java:2106)
        at org.apache.maven.surefire.junit.JUnitTestSet.createInstanceFromSuiteMethod(JUnitTestSet.java:176)
        at org.apache.maven.surefire.junit.JUnitTestSet.constructTestObject(JUnitTestSet.java:140)
        at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:197)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:115)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:102)
        at org.apache.maven.surefire.Surefire.run(Surefire.java:180)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
        at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
[ERROR] There are test failures.
```

**Comment by algomaster99** [comment]
Cannot reproduce.
![image](https://user-images.githubusercontent.com/35191225/236317131-3a596b21-0e95-42c8-8717-d705796508b7.png)
