### ISSUE TITLE
Error at instruction 36: Argument 1: expected I, but found `Throwable`

### ISSUE THREAD

**Issue by algomaster99** [ASSERT-KTH/collector-sahab#218]
## patch1-Time-15-Elixir_c24932ee3f562f66f282ad80d5d9d3a0504917c6

I am pretty sure I fixed this in https://github.com/ASSERT-KTH/collector-sahab/pull/203.

**Stacktrace**

```sh
Running org.joda.time.field.TestFieldUtils
rtf.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 36: Argument 1: expected I, but found Ljava/lang/ArithmeticException;
        at rtf.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:269)
        at rtf.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
        at rtf.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1032)
        at io.github.chains_project.collector.CollectorAgent.getBytes(CollectorAgent.java:179)
        at io.github.chains_project.collector.CollectorAgent$1.transform(CollectorAgent.java:80)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.joda.time.field.TestFieldUtils.testSafeAddLong(TestFieldUtils.java:91)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at junit.framework.TestCase.runTest(TestCase.java:164)
        at junit.framework.TestCase.runBare(TestCase.java:130)
        at junit.framework.TestResult$1.protect(TestResult.java:106)
        at junit.framework.TestResult.runProtected(TestResult.java:124)
        at junit.framework.TestResult.run(TestResult.java:109)
        at junit.framework.TestCase.run(TestCase.java:120)
        at junit.framework.TestSuite.runTest(TestSuite.java:230)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
        at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:121)
        at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:98)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
Caused by: rtf.org.objectweb.asm.tree.analysis.AnalyzerException: Argument 1: expected I, but found Ljava/lang/ArithmeticException;
        at rtf.org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:401)
        at rtf.org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:44)
        at rtf.org.objectweb.asm.tree.analysis.Frame.executeInvokeInsn(Frame.java:684)
        at rtf.org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:609)
        at rtf.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:165)
        ... 45 more
rtf.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 288: Cannot pop operand off an empty stack.
        at rtf.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:273)
        at rtf.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
        at rtf.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1032)
        at io.github.chains_project.collector.CollectorAgent.getBytes(CollectorAgent.java:179)
        at io.github.chains_project.collector.CollectorAgent$1.transform(CollectorAgent.java:80)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.joda.time.field.TestFieldUtils.testSafeAddLong(TestFieldUtils.java:91)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at junit.framework.TestCase.runTest(TestCase.java:164)
		at junit.framework.TestCase.runBare(TestCase.java:130)
        at junit.framework.TestResult$1.protect(TestResult.java:106)
        at junit.framework.TestResult.runProtected(TestResult.java:124)
        at junit.framework.TestResult.run(TestResult.java:109)
        at junit.framework.TestCase.run(TestCase.java:120)
        at junit.framework.TestSuite.runTest(TestSuite.java:230)
        at junit.framework.TestSuite.run(TestSuite.java:225)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
        at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:121)
        at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:98)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
Caused by: java.lang.IndexOutOfBoundsException: Cannot pop operand off an empty stack.
        at rtf.org.objectweb.asm.tree.analysis.Frame.pop(Frame.java:258)
        at rtf.org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:396)
        at rtf.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:165)
        ... 45 more
rtf.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 103: Cannot pop operand off an empty stack.
        at rtf.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:273)
        at rtf.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1074)
        at rtf.org.objectweb.asm.util.CheckClassAdapter.verify(CheckClassAdapter.java:1032)
        at io.github.chains_project.collector.CollectorAgent.getBytes(CollectorAgent.java:179)
        at io.github.chains_project.collector.CollectorAgent$1.transform(CollectorAgent.java:80)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.joda.time.field.TestFieldUtils.testSafeAddLong(TestFieldUtils.java:91)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
        at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:121)
        at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:98)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
Caused by: java.lang.IndexOutOfBoundsException: Cannot pop operand off an empty stack.
        at rtf.org.objectweb.asm.tree.analysis.Frame.pop(Frame.java:258)
        at rtf.org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:396)
        at rtf.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:165)
        ... 45 more
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.159 sec <<< FAILURE!

Results :

Tests in error:
  testSafeAddLong(org.joda.time.field.TestFieldUtils): Operand stack underflow(..)
  testSafeAddInt(org.joda.time.field.TestFieldUtils): Operand stack underflow(..)
  testSafeSubtractLong(org.joda.time.field.TestFieldUtils): Operand stack underflow(..)
  testSafeMultiplyLongLong(org.joda.time.field.TestFieldUtils): Operand stack underflow(..)
  testSafeMultiplyLongInt(org.joda.time.field.TestFieldUtils): Operand stack underflow(..)

Tests run: 5, Failures: 0, Errors: 5, Skipped: 0
```

**Comment by algomaster99** [comment]
I cannot reproduce the error on my local machine. In fact, we get an execution difference on my machine.

**Command to reproduce**
```sh
java -jar main/target/collector-sahab-0.4.2-SNAPSHOT-jar-with-dependencies.jar -p /home/aman/experiments/drr-execdiff/Time-15 -c src/main/java/org/joda/time/field/FieldUtils.java  --slug ASSERT-KTH/collector-sahab-experiments -l e5d67a8 -r c24932ee3f562f66f282ad80d5d9d3a0504917c6 --execution-depth 0 --selected-tests org.joda.time.field.TestFieldUtils --output-path output.html
```

![image](https://user-images.githubusercontent.com/35191225/235719243-0518511b-486e-410f-b823-e5020beb5cbd.png)
