### ISSUE TITLE
GHHelper throws `NullPointerException`

### ISSUE THREAD

**Issue by algomaster99** [ASSERT-KTH/collector-sahab#221]
## patch15-Math-85-SequenceR_c54bd1816025f33a2ffaa092966e41f9b259f0dd 

**Stacktrace**

```sh
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}) on port 19927
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Apr 26, 2023 3:23:55 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 112, so returning the closest version found: 110
java.lang.NullPointerException
        at io.github.chains_project.tracediff.sharedutils.GHHelper.getGHDiff(GHHelper.java:557)
        at io.github.chains_project.tracediff.statediff.ui.StateDiffUIManipulator.addStateDiffToExecDiffUI(StateDiffUIManipulator.java:64)
        at io.github.chains_project.tracediff.statediff.StateDiffCommand.call(StateDiffCommand.java:73)
        at io.github.chains_project.tracediff.statediff.StateDiffCommand.call(StateDiffCommand.java:9)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.github.chains_project.tracediff.ExecDiffMain.main(ExecDiffMain.java:18)
        at io.github.chains_project.cs.Main.call(Main.java:179)
        at io.github.chains_project.cs.Main.call(Main.java:30)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.github.chains_project.cs.Main.main(Main.java:89)
```

**Comment by khaes-kth** [comment]
When I run it locally, it works. Also, for all depths, except dp=0, it has also worked on the repairnator machine. I guess that we get this for dp=0 is that Selenium has failed to render the page or some connection issue.

So, I'm closing this...
