### ISSUE TITLE
MatchLineFinder failing on constructor method

### ISSUE THREAD

**Issue by khaes-kth** [ASSERT-KTH/collector-sahab#238]
When run on [patch5-Math-95-JGenProg2017](https://github.com/ASSERT-KTH/collector-sahab-experiments/commit/6bf70cd6214303b773d2091b60e93ed0a52caea1) with depth=2, MatchLineFinder throws a runtime error:

```
java.lang.RuntimeException: Could not find mapping for <init> with start line 93
        at io.github.chains_project.mlf.MatchedLineFinder.findMapping(MatchedLineFinder.java:241)
        at io.github.chains_project.mlf.MatchedLineFinder.findMethods(MatchedLineFinder.java:181)
        at io.github.chains_project.mlf.MatchedLineFinder.invoke(MatchedLineFinder.java:34)
        at io.github.chains_project.cs.Main.call(Main.java:112)
        at io.github.chains_project.cs.Main.call(Main.java:28)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.github.chains_project.cs.Main.main(Main.java:93)
```

@algomaster99 It seems to be related to constructor method changes.

**Comment by algomaster99** [comment]
It works in the latest SNAPSHOT version, so I am assuming it will also work with `0.5.0`.

Command to reproduce
```sh
java -jar main/target/collector-sahab-0.5.1-SNAPSHOT-jar-with-dependencies.jar  -p /home/aman/experiments/drr-execdiff/Math-86 -c src/java/org/apache/commons/math/linear/CholeskyDecompositionImpl.java  --slug ASSERT-KTH/collector-sahab-experiments -l e5d67a8 -r 6bf70cd6214303b773d2091b60e93ed0a52caea1 --execution-depth 2 --selected-tests org.apache.commons.math.linear.CholeskyDecompositionImplTest --output-path output.html
```

**Comment by khaes-kth** [comment]
Cool! Thanks.
